projects:
  nintenlife:
    schemaPath: src/graphql/schema.json
    includes:
      - src/services/graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/services
